set(TEST_LIBRARY_DIR ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/WPEAPITests)
set(TEST_BINARY_DIR ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/TestCyberKitAPI/WPE)

list(APPEND CyberKitGLibAPITests_SOURCES
    ${TOOLS_DIR}/TestCyberKitAPI/glib/CyberKitGLib/wpe/WebViewTestWPE.cpp
)

list(APPEND CyberKitGLibAPITests_INCLUDE_DIRECTORIES
    ${DERIVED_SOURCES_WPE_API_DIR}
    ${FORWARDING_HEADERS_WPE_DIR}
    ${FORWARDING_HEADERS_WPE_EXTENSION_DIR}
    ${FORWARDING_HEADERS_WPE_DOM_DIR}
    ${TOOLS_DIR}/wpe/backends
)

list(APPEND CyberKitGLibAPITests_SYSTEM_INCLUDE_DIRECTORIES
    ${WPE_INCLUDE_DIRS}
    ${WPEBACKEND_FDO_INCLUDE_DIRS}
)

list(APPEND CyberKitGLibAPITest_LIBRARIES
    ${WPE_LIBRARIES}
    ${WPEBACKEND_FDO_LIBRARIES}
    WPEToolingBackends
)
