if (NOT BMALLOC_DIR)
    set(BMALLOC_DIR "${CMAKE_SOURCE_DIR}/Source/bmalloc")
endif ()
if (NOT WTF_DIR)
    set(WTF_DIR "${CMAKE_SOURCE_DIR}/Source/WTF")
endif ()
if (NOT JAVASCRIPTCORE_DIR)
    set(JAVASCRIPTCORE_DIR "${CMAKE_SOURCE_DIR}/Source/JavaScriptCore")
endif ()
if (NOT WEBCORE_DIR)
    set(WEBCORE_DIR "${CMAKE_SOURCE_DIR}/Source/CyberCore")
endif ()
if (NOT PAL_DIR)
    set(PAL_DIR "${CMAKE_SOURCE_DIR}/Source/CyberCore/PAL")
endif ()
if (NOT WEBKITLEGACY_DIR)
    set(WEBKITLEGACY_DIR "${CMAKE_SOURCE_DIR}/Source/CyberKitLegacy")
endif ()
if (NOT WEBKIT_DIR)
    set(WEBKIT_DIR "${CMAKE_SOURCE_DIR}/Source/CyberKit")
endif ()
if (NOT THIRDPARTY_DIR)
    set(THIRDPARTY_DIR "${CMAKE_SOURCE_DIR}/Source/ThirdParty")
endif ()
if (NOT TOOLS_DIR)
    set(TOOLS_DIR "${CMAKE_SOURCE_DIR}/Tools")
endif ()
if (NOT WEBDRIVER_DIR)
    set(WEBDRIVER_DIR "${CMAKE_SOURCE_DIR}/Source/WebDriver")
endif ()
if (NOT WEBINSPECTORUI_DIR)
    set(WEBINSPECTORUI_DIR "${CMAKE_SOURCE_DIR}/Source/WebInspectorUI")
endif ()

set(WTF_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WTF/DerivedSources")
set(JavaScriptCore_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/JavaScriptCore/DerivedSources")
set(PAL_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/PAL/DerivedSources")
set(CyberCore_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/CyberCore/DerivedSources")
set(WebDriver_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WebDriver/DerivedSources")
set(CyberKitLegacy_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/CyberKitLegacy/DerivedSources")
set(CyberKit_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/CyberKit/DerivedSources")
set(WebInspectorUI_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WebInspectorUI/DerivedSources")
set(MiniBrowser_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/MiniBrowser/DerivedSources")
set(TestRunnerShared_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/TestRunnerShared/DerivedSources")
set(DumpRenderTree_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/DumpRenderTree/DerivedSources")
set(CyberKitTestRunner_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/CyberKitTestRunner/DerivedSources")

set(bmalloc_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/bmalloc/Headers")
set(ANGLE_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/ANGLE/Headers")
set(WTF_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/WTF/Headers")
set(JavaScriptCore_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/JavaScriptCore/Headers")
set(JavaScriptCore_PRIVATE_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/JavaScriptCore/PrivateHeaders")
set(PAL_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/PAL/Headers")
set(CyberCore_PRIVATE_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/CyberCore/PrivateHeaders")
set(CyberKitLegacy_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/CyberKitLegacy/Headers")
set(CyberKit_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/CyberKit/Headers")
set(CyberKit_PRIVATE_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/CyberKit/PrivateHeaders")

set(WTF_SCRIPTS_DIR "${CMAKE_BINARY_DIR}/WTF/Scripts")
set(JavaScriptCore_SCRIPTS_DIR "${CMAKE_BINARY_DIR}/JavaScriptCore/Scripts")
