set(WTF_PLATFORM_WIN_CAIRO 1)

include(OptionsWin)

find_package(Cairo 1.15.12 REQUIRED)
find_package(CURL 7.60.0 REQUIRED)
find_package(ICU REQUIRED COMPONENTS data i18n uc)
find_package(JPEG 1.5.2 REQUIRED)
find_package(LibXml2 2.9.7 REQUIRED)
find_package(OpenSSL 2.0.0 REQUIRED)
find_package(PNG 1.6.34 REQUIRED)
find_package(Sqlite 3.23.1 REQUIRED)
find_package(ZLIB 1.2.11 REQUIRED)
find_package(LibPSL 0.20.2 REQUIRED)

if (ENABLE_XSLT)
    find_package(LibXslt 1.1.32 REQUIRED)
endif ()

# Optional packages
find_package(OpenJPEG 2.3.1)
if (OpenJPEG_FOUND)
    SET_AND_EXPOSE_TO_BUILD(USE_OPENJPEG ON)
endif ()

find_package(WebP 1.0.0)
if (WEBP_FOUND)
    SET_AND_EXPOSE_TO_BUILD(USE_WEBP ON)
endif ()

SET_AND_EXPOSE_TO_BUILD(USE_CAIRO ON)
SET_AND_EXPOSE_TO_BUILD(USE_CF ON)
SET_AND_EXPOSE_TO_BUILD(USE_CURL ON)
SET_AND_EXPOSE_TO_BUILD(USE_TEXTURE_MAPPER ON)
SET_AND_EXPOSE_TO_BUILD(USE_TEXTURE_MAPPER_GL ON)
SET_AND_EXPOSE_TO_BUILD(USE_MEDIA_FOUNDATION ON)
SET_AND_EXPOSE_TO_BUILD(USE_INSPECTOR_SOCKET_SERVER ${ENABLE_REMOTE_INSPECTOR})

set(ENABLE_GRAPHICS_CONTEXT_3D ON)
set(ENABLE_WEBKIT ON)

set(USE_ANGLE_EGL ON)

set(COREFOUNDATION_LIBRARY CFlite)

SET_AND_EXPOSE_TO_BUILD(ENABLE_DEVELOPER_MODE ${DEVELOPER_MODE})

add_definitions(-DWTF_PLATFORM_WIN_CAIRO=1)
add_definitions(-DNOCRYPT)

# Override headers directories
set(ANGLE_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/ANGLE/Headers)
set(WTF_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/WTF/Headers)
set(CyberScriptCore_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/CyberScriptCore/Headers)
set(CyberScriptCore_PRIVATE_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/CyberScriptCore/PrivateHeaders)
set(PAL_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/PAL/Headers)
set(CyberCore_PRIVATE_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/CyberCore/PrivateHeaders)
set(CyberKitLegacy_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/CyberKitLegacy/Headers)
set(CyberKit_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/CyberKit/Headers)
set(CyberKit_PRIVATE_FRAMEWORK_HEADERS_DIR ${CMAKE_BINARY_DIR}/CyberKit/PrivateHeaders)

# Override derived sources directories
set(WTF_DERIVED_SOURCES_DIR ${CMAKE_BINARY_DIR}/WTF/DerivedSources)
set(CyberScriptCore_DERIVED_SOURCES_DIR ${CMAKE_BINARY_DIR}/CyberScriptCore/DerivedSources)
set(CyberCore_DERIVED_SOURCES_DIR ${CMAKE_BINARY_DIR}/CyberCore/DerivedSources)
set(CyberKitLegacy_DERIVED_SOURCES_DIR ${CMAKE_BINARY_DIR}/CyberKitLegacy/DerivedSources)
set(CyberKit_DERIVED_SOURCES_DIR ${CMAKE_BINARY_DIR}/CyberKit/DerivedSources)

# Override scripts directories
set(WTF_SCRIPTS_DIR ${CMAKE_BINARY_DIR}/WTF/Scripts)
set(CyberScriptCore_SCRIPTS_DIR ${CMAKE_BINARY_DIR}/CyberScriptCore/Scripts)

# Override library types
set(CyberCore_LIBRARY_TYPE OBJECT)
set(CyberCoreTestSupport_LIBRARY_TYPE OBJECT)
