#!/bin/bash

# Make sure that Homebrew is in the PATH if it could be
PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

# Check initial conditions
if [[ $EUID -eq 0 ]]; then
    echo "[!] Please don't run this script as root!"
    exit
fi

if [[ $(command -v brew) == "" ]]; then
    echo "[!] Homebrew not installed!"
    echo "[!] PATH is $PATH"
    echo "[!] Please run the following command!"
    echo '[!] /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
    exit
else
    echo "[§] Found Homebrew"
    if brew ls --versions ldid >/dev/null; then
        echo "[§] Found ldid"
    else
        echo "[§] Attempting to install script dependencies"
        brew install coreutils dpkg ldid
    fi
fi

# Prepare payload directory
SCRIPT_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
cd $SCRIPT_DIR

# Get command-line arguments (note relative paths are relative to this script's directory)

# Argument help:
# $1 = name of folder within resources, will also be used temporarily to name DEB file
# $2 = original copy of application, will not be modified
# $3 = WebKit framework location (provide a build products directory generated by Xcode or .deb of a MobileMiniBrowser release)
# $4 = directory where resources are located
# Returns: DEB and TIPA files, and the Payload directory, in the directory containing $2

# Example invocation (each argument wrapped to another line for length purposes):
# ~/Documents/git/CyberKit/Tools/MobileMiniBrowser/script_fakesigner.sh
# fennec-16
# ~/Downloads/Firefox_131.4_decrypted.ipa
# ~/Downloads/com.matthewbenedict.mobileminibrowser+16_0.0.9-nightly.01_iphoneos-arm.deb
# ~/Documents/git/firefox-ios

DIR_NAME=$1

safe_app=$(realpath $2)
echo "[§] Application:" $safe_app
if [ ! -e $safe_app ]; then
    echo "[!] Could not locate application at expected location"
    exit 1
fi

webkit_build=$(realpath $3)
echo "[§] WebKit build directory:" $webkit_build
if [ ! -e $webkit_build ]; then
    echo "[!] Could not locate WebKit build directory at expected location"
    exit 1
fi

DEBIAN_FILES=$(realpath $4)/resources/$DIR_NAME
echo "[§] Resources directory:" $DEBIAN_FILES
if [ ! -d $DEBIAN_FILES ]; then
    echo "[!] Could not locate resources directory at expected location"
    exit 1
fi

# Initialization
rm -rf $(dirname $safe_app)/Payload
cd $(dirname $safe_app) || exit 1
if [[ $safe_app == *.app ]]; then
    if [ ! -d $safe_app ]; then
        echo "[!] Expected WebKit build directory to be a .app bundle, but couldn't find it"
        exit 1
    fi
    mkdir Payload
    cp -R $safe_app $(dirname $safe_app)/Payload
elif [[ $safe_app == *.ipa ]]; then
    if [ ! -f $safe_app ]; then
        echo "[!] Expected WebKit build directory to be a .ipa file, but couldn't find it"
        exit 1
    fi
    unzip $safe_app
else
    echo "[!] No .ipa file supplied!"
    exit 1
fi

cd Payload
app=$(ls -1 -d *.app)
rpath=$(dirname $safe_app)/Payload/$app/Frameworks

if [[ $webkit_build == *.deb ]]; then
    if [ ! -f $webkit_build ]; then
        echo "[!] Expected WebKit build directory to be a .deb file, but couldn't find it"
        exit 1
    fi
    app_dir=$rpath/../extract
    dpkg-deb -x $webkit_build $app_dir
    while [[ $app_dir != *.app ]]; do
        app_dir=$(ls -1 -d $app_dir/*)
    done
    rm -rf $app_dir/Frameworks/MobileMiniBrowser.framework
    cp -R $app_dir/Frameworks/* $rpath
    rm -rf $rpath/../extract
else
    if [ ! -d $webkit_build ]; then
        echo "[!] Expected WebKit build directory to be a generated directory, but couldn't find it"
        exit 1
    fi
    # Copy ICU data and frameworks
    cp -R $webkit_build/JavaScriptCore.framework $webkit_build/Web*.framework $rpath
    
    icu_source=$webkit_build/../../Source/WTF/icu
    #cp $icu_source/build.noindex/ios_arm64/data/out/tmp/*.dat $rpath
    cp $icu_source/libunicode.dylib $rpath
    
    mkdir $rpath/WebCore.framework/Frameworks
    cp $webkit_build/libANGLE-shared.dylib $webkit_build/libwebrtc.dylib $rpath/WebCore.framework/Frameworks
    
    # Load Swift overlay and libWebKitSwift, which are apparently separate things.
    # See https://github.com/WebKit/WebKit/pull/34598 about removing the Swift overlay.
    rm -rf $rpath/WebKit.framework/Frameworks && mkdir $rpath/WebKit.framework/Frameworks
    cp $webkit_build/libswiftWebKit.dylib $rpath
    cp $webkit_build/libWebKitSwift.dylib $rpath/WebKit.framework/Frameworks
    
    # Load adattributiond and webpushd
    rm -rf $rpath/WebKit.framework/Daemons && mkdir $rpath/WebKit.framework/Daemons
    cp $webkit_build/adattributiond $webkit_build/webpushd $rpath/WebKit.framework/Daemons
    
    # Load XPC services
    rm -rf $rpath/WebKit.framework/XPCServices && mkdir $rpath/WebKit.framework/XPCServices
    cp -R $webkit_build/*.xpc $rpath/WebKit.framework/XPCServices
fi

# Fakesign
cp $SCRIPT_DIR/script_fakesigner.entitlements .

binaries=(
    $rpath/*.dylib
    $rpath/WebCore.framework/Frameworks/*.dylib
    $rpath/WebKit.framework/Frameworks/*.dylib
    $rpath/WebKit.framework/XPCServices/*.xpc
    $rpath/*.framework
    $app
)
binaries_len=${#binaries[@]}

system_paths=(
    /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
    /System/Library/PrivateFrameworks/WebCore.framework/WebCore
    /System/Library/PrivateFrameworks/WebKitLegacy.framework/WebKitLegacy
    /System/Library/Frameworks/WebKit.framework/WebKit
    /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib
    /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libANGLE-shared.dylib
    /System/Library/PrivateFrameworks/WebGPU.framework/WebGPU
    /System/Library/Frameworks/WebKit.framework/Frameworks/libWebKitSwift.dylib
    /usr/lib/swift/libswiftWebKit.dylib
    /usr/lib/libicucore.A.dylib
)
system_paths_len=${#system_paths[@]}

relative_paths=(
    @rpath/JavaScriptCore.framework/JavaScriptCore
    @rpath/WebCore.framework/WebCore
    @rpath/WebKitLegacy.framework/WebKitLegacy
    @rpath/WebKit.framework/WebKit
    @rpath/WebCore.framework/Frameworks/libwebrtc.dylib
    @rpath/WebCore.framework/Frameworks/libANGLE-shared.dylib
    @rpath/WebGPU.framework/WebGPU
    @rpath/WebKit.framework/Frameworks/libWebKitSwift.dylib
    @rpath/libswiftWebKit.dylib
    @rpath/libunicode.dylib
)
relative_paths_len=${#relative_paths[@]}

if ((system_paths_len != relative_paths_len)); then exit 1; fi

# This script can alleviate the need to properly set the install name in CyberKit itself
# We can fix that with the script though
for (( i = 0; i < $relative_paths_len; i++ )); do
    relative_path=${relative_paths[$i]}
    app_path=$(echo $relative_path | sed 's|@rpath|'$rpath'|')
    if [ -f $app_path ]; then
        install_name_tool -id $relative_path $app_path
    fi
done

for (( i = 0; i < $binaries_len; i++ )); do

    # If this is a bundle directory, get the real executable
    bin=${binaries[$i]}
    base=$(basename $bin)
    if [[ $base == *.* ]] && [ -d $bin ]; then
        bin=$bin/$(echo $base | sed 's/\(.*\)\.\(.*\)/\1/')
    fi
    
    # Confirm there is really a file there, it might happen that we have an empty wildcard
    user_bin=$(echo $bin | sed "s|"$rpath"|@rpath|")
    if [ -f $bin ]; then
        echo "["$(($i + 1))"/"$binaries_len"] Fakesigning" $user_bin
        
        # Get entitlements
        static_ents=$(<./script_fakesigner.entitlements)
        static_ents=${static_ents%\<\/dict\>*}
        existing_ents=$(ldid -e $bin)
        existing_ents=${existing_ents#*\<dict\>}
        existing_ents=${existing_ents%\<\/dict\>*}
        new_ents=bin_$i.entitlements
        echo ${static_ents}${existing_ents}$'\n</dict>\n</plist>' > $new_ents
    
        # Correct dependency errors
        for (( j = 0; j < $system_paths_len; j++ )); do
            if otool -l $bin | grep ${system_paths[$j]}; then
                echo "[§] Changing dependency" ${system_paths[$j]} "to" ${relative_paths[$j]} "in" $bin
                install_name_tool -change ${system_paths[$j]} ${relative_paths[$j]} $bin
            fi
        done
    
        # Fakesign
        ldid -S$new_ents $bin
    else
        echo "["$(($i + 1))"/"$binaries_len"] Warning: A path was specified but there is no file at" $user_bin
    fi
done

rm *.entitlements

# Setup for DEB packaging
cd ..
rm -f *.deb || true
if [[ $DIR_NAME == *"+"* ]]; then
    if [[ ${DIR_NAME#*+} -le 10 ]]; then
        # We manually stash WebKit on legacy iOS because it doesn't fit in the root partition
        echo "[*] Using stashed application path"
        APPLICATION_PATH=$DIR_NAME/private/var/containers/Bundle/Application/DEADBEEF-DEAD-BEEF-DEAD-BEEFC1B34800
    else
        # Put WebKit in the rootful application path
        echo "[*] Using rootful application path"
        APPLICATION_PATH=$DIR_NAME/Applications
    fi
else
    echo "[*] Using rootless application path"
    APPLICATION_PATH=$DIR_NAME/private/var/jb/Applications
fi

# Package into DEB
echo "[*] Creating DEB..."
mkdir $DIR_NAME
if [[ $DIR_NAME == *"+"* ]] && [[ ${DIR_NAME#*+} -le 10 ]]; then
    mkdir $DIR_NAME/private
    mkdir $DIR_NAME/private/var
    mkdir $DIR_NAME/private/var/containers
    mkdir $DIR_NAME/private/var/containers/Bundle
    mkdir $DIR_NAME/private/var/containers/Bundle/Application
elif [[ $DIR_NAME != *"+"* ]]; then
    mkdir $DIR_NAME/private
    mkdir $DIR_NAME/private/var
    mkdir $DIR_NAME/private/var/jb
fi

mv Payload $APPLICATION_PATH
mkdir $DIR_NAME/DEBIAN
cp -R $DEBIAN_FILES/* $DIR_NAME/DEBIAN
find . -name ".DS_Store" -delete

if [[ "$DIR_NAME" == *"+"* ]] && [[ ${DIR_NAME#* } -le 10 ]]; then
    cp $SCRIPT_DIR/uicache/cyberuicache $APPLICATION_PATH
    cp $SCRIPT_DIR/script_fakesigner.entitlements $APPLICATION_PATH
    cp $SCRIPT_DIR/uicache/.com.apple.mobile_container_manager.metadata.plist $APPLICATION_PATH
    echo "[*] Forcing gzip compression for legacy iOS"
    dpkg-deb -Zgzip --build $DIR_NAME && dpkg-name $DIR_NAME.deb
else
    echo "[*] Using default compression for non-legacy iOS"
    dpkg-deb -b $DIR_NAME && dpkg-name $DIR_NAME.deb
fi
mv $APPLICATION_PATH Payload
rm -rf $DIR_NAME

# Package into IPA
TIPA_NAME=$(echo *.deb | sed 's/_[a-z].*//' | sed 's/\+\([0-9]\)/\1/' | sed 's/-\([0-9]\)/\1/')
echo "[*] Creating IPA..."
rm -f *.tipa || true
zip -r -y "$TIPA_NAME.tipa" Payload
echo "[*] Created $TIPA_NAME.tipa"