set(TEST_LIBRARY_DIR ${CMAKE_LIBRARY_OUTPUT_DIRECTORY}/WPEAPITests)
set(TEST_BINARY_DIR ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/TestCyberKitAPI/WPE)

list(APPEND CyberKitGLibAPITests_SOURCES
    ${TOOLS_DIR}/TestCyberKitAPI/glib/CyberKitGLib/wpe/WebViewTestWPE.cpp
)

list(APPEND CyberKitGLibAPITests_INCLUDE_DIRECTORIES
    ${DERIVED_SOURCES_WPE_API_DIR}
    ${FORWARDING_HEADERS_WPE_DIR}
    ${FORWARDING_HEADERS_WPE_DOM_DIR}
    ${FORWARDING_HEADERS_WPE_EXTENSION_DIR}
)

list(APPEND CyberKitGLibAPITests_SYSTEM_INCLUDE_DIRECTORIES
    ${WPEBACKEND_FDO_INCLUDE_DIRS}
)

list(APPEND CyberKitGLibAPITestsCore_LIBRARIES
    Cairo::Cairo
    CyberKit::WPEToolingBackends
)

list(APPEND CyberKitGLibAPITest_LIBRARIES
    ${WPEBACKEND_FDO_LIBRARIES}
    Cairo::Cairo
    WPE::libwpe
    CyberKit::WPEToolingBackends
)
