# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: push

jobs:
  build:
    permissions: # Read more at : https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      contents: write
    name: Create Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'CST'
          sha: '44a5ba60ecc71997f485623141f7e133cec2d1d6'